### ISSUE TITLE
원제, 트위터 기능 추가 후 생긴 오류

### ISSUE THREAD

**Issue by CodeName393** [anissia-net/anissia-core#17]
제목 자제가 영어만 있어서 원제는 안 넣고 트위터만 따로 넣으려 하니 수정이 불가능합니다.
![화면 캡처 2022-10-22 115429](https://user-images.githubusercontent.com/62503817/197316019-eb43f703-8dc6-4c7a-9f01-40230bfd07f1.png)

**Comment by ac-saro** [comment]
https://github.com/anissia-net/anissia-core/commit/2c5397311db157ac61e0c14ed19cd0dcfdf3185f
원제를 기본값에서 제외하였습니다.
